services:
  nvidia-attest: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nvidia-attest

  targon:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./targon
    env_file: .env
