services:
  nvidia-attest: 
    restart: always
    image: manifoldlabs/targon-nvidia-attest:latest
    build:
      dockerfile: Dockerfile
      context: ./nvidia-attest

  targon:
    restart: always
    image: manifoldlabs/targon:latest
    build:
      dockerfile: Dockerfile
      context: ./targon
    env_file: .env
